[package]
name = "hasanlang"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
clap = { version = "4.3.12", features = ["derive"] }
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm15-0", "target-x86"] }
pest = "2.7.0"
pest_derive = { version = "2.7", features = ["grammar-extras"] }
rand = "0.8.5"
strum = "0.25.0"
strum_macros = "0.25.1"
