[package]
name = "hasan_analyzer"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hasan_parser = { path = "../hasan_parser" }
hasan_hir = { path = "../hasan_hir" }
hasan_intrinsics = { path = "../hasan_intrinsics" }
anyhow = "1.0.72"
strum = "0.25.0"
strum_macros = "0.25.1"
paste = "1.0.14"
indent = "0.1.1"