[package]
name = "hasan_hir"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hasan_parser = { path = "../hasan_parser" }
strum = "0.25.0"
strum_macros = "0.25.1"
indent = "0.1.1"